config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  # root 'work#index'
  # match 'work/index', to: 'work#index', via: 'get'
  # match 'work', to: 'work#index', via: 'get'

# 'get' = :get

  # match 'work/choose_theme', to: 'work#choose_theme', via: :get, :as => 'choose_theme'

  match 'work/display_theme', to: 'work#display_theme', via: :post

  resources :themes
  resources :values
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  # root 'main#index'
  # get 'main/index'

  # match 'main/help', to: 'main#help', via: 'get'

  # get 'main/contacts'

  namespace :api, defaults: { format: :json } do
    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end

  match 'index',     to: 'main#index',      via: :get
  match 'about',     to: 'main#about',      via: :get
  match 'help',      to: 'main#help',       via: :get
  match 'contacts',  to: 'main#contacts',   via: :get

  match 'work',             to: 'work#index',             via: :get
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post

  match 'signup',     to: 'users#new',         via: 'get'
  match 'signin',     to: 'sessions#new',      via: 'get'
  match 'signout',    to: 'sessions#destroy',  via: 'delete'

  match 'results_list',     to: 'work#results_list', via: :get

  match 'save_value',       to: 'api/api#save_value',   via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :values, dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def self.all_cached
    # ids = Rails.cache.fetch('User.all') do
    #   User.all.pluck(:id)
    # end
    # User.find(ids)
    Rails.cache.fetch('User.all') { all }
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all_cached
  end

  # GET /users/1
  # GET /users/1.json
  def show
    user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        flash.now[:alert] = "Bad registration"
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label t('.name')
    = f.text_field :name
  .field
    = f.label t('.email')
    = f.text_field :email
  .field
    = f.label t('.password')
    = f.password_field :password
  .field
    = f.label t('.password_confirmation')
    = f.password_field :password_confirmation

  .actions
    = f.submit t(".create_account"), class: "btn btn-large btn-primary"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.en.html.haml
.container
  %h1 User list

  %span.add_user
    = link_to t('.new_user'), new_user_path
  %br

  %table
    %thead
      %tr
        %th Name
        %th Email
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= link_to t('.show'), user
          %td= link_to t('.edit'), edit_user_path(user)
          %td= link_to t('.destroy'), user, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

app/views/users/index.ru.html.haml
.container
  %h1 Список пользователей

  %span.add_user
    = link_to t('.new_user'), new_user_path
  %br

  %table
    %thead
      %tr
        %th Имя
        %th Email
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= link_to t('.show'), user
          %td= link_to t('.edit'), edit_user_path(user)
          %td= link_to t('.destroy'), user, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

app/views/users/new.html.haml
-provide(:title, "Sign up")

.container
  %h1= t('.new_user_sign_up')

  = render 'form'

-#= link_to 'Back', users_path

  = link_to t('.back'), root_path, :class => "ui_link"

app/views/users/show.html.haml
%p#notice= notice

.container
  .show_user
    .row
      %aside.span4
        %section
          = gravatar_for @user
          .profile_login
            %p
              = @user.name
    .profile_email
      %b= t('.email')
      = @user.email

    = link_to t('.work'), work_path, class: "btn btn-lg btn-primary"

  .profile_control
    = link_to t('.edit'), edit_user_path(@user)
    \|
    = link_to t('.user_list'), users_path