config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  # root 'work#index'
  # match 'work/index', to: 'work#index', via: 'get'
  # match 'work', to: 'work#index', via: 'get'

# 'get' = :get

  # match 'work/choose_theme', to: 'work#choose_theme', via: :get, :as => 'choose_theme'

  match 'work/display_theme', to: 'work#display_theme', via: :post

  resources :themes
  resources :values
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  # root 'main#index'
  # get 'main/index'

  # match 'main/help', to: 'main#help', via: 'get'

  # get 'main/contacts'

  namespace :api, defaults: { format: :json } do
    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end

  match 'index',     to: 'main#index',      via: :get
  match 'about',     to: 'main#about',      via: :get
  match 'help',      to: 'main#help',       via: :get
  match 'contacts',  to: 'main#contacts',   via: :get

  match 'work',             to: 'work#index',             via: :get
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post

  match 'signup',     to: 'users#new',         via: 'get'
  match 'signin',     to: 'sessions#new',      via: 'get'
  match 'signout',    to: 'sessions#destroy',  via: 'delete'

  match 'results_list',     to: 'work#results_list', via: :get

  match 'save_value',       to: 'api/api#save_value',   via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.en.html.haml
%footer.footer
  .footer_container
    %i.fa.fa-flag.iconsMain
      Experteese

    .footer_menu
      %nav
        %ul
          %li
            =link_to t('.about'), about_path
          %li
            =link_to t('.contacts'), contacts_path
          %li
            %a{:href => "http://news.railstutorial.org/"} News

    .socials
      = link_to image_tag("facebook.png", alt: "", title: "Facebook")
      = link_to image_tag("twitter.png", alt: "", title: "Twitter")
      = link_to image_tag("skype.png", alt: "", title: "Skype")

    %i.fa.fa-copyright.iconsMain
      2016 Experteese. All rights reserved

app/views/shared/_footer.ru.html.haml
%footer.footer
  .footer_container
    %i.fa.fa-flag.iconsMain
      Experteese

    .footer_menu
      %nav
        %ul
          %li
            =link_to t('.about'), about_path
          %li
            =link_to t('.contacts'), contacts_path
          %li
            %a{:href => "http://news.railstutorial.org/"} Новости

    .socials
      = link_to image_tag("facebook.png", alt: "", title: "Facebook")
      = link_to image_tag("twitter.png", alt: "", title: "Twitter")
      = link_to image_tag("skype.png", alt: "", title: "Skype")

    %i.fa.fa-copyright.iconsMain
      2016 Experteese. Все права защищены

app/views/shared/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container.header
    .rails_logo
      = link_to image_tag("ruby.png", alt: "Rails logo", width: "45px")
    = link_to t('.logo_title'), root_path, id: "logo"

    %nav
      %ul.nav.navbar-nav.pull-left
        %li
          =link_to t('.home'), root_path
        %li
          =link_to t('.help'), help_path
        -#%li
        -#  =link_to 'Contacts', main_help_path
        -#%li
        -#  =link_to 'About', main_about_path
        - if signed_in?
          %li.logged
            #{current_user.email}
          = gravatar_for current_user
          %li#fat-menu.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %p
                = t('.person')
                %b.caret
            %ul.dropdown-menu
              %li= link_to t('.profile'), current_user
              %li= link_to t('.settings'), '#'
              %li.divider
              %li= link_to t('.sign_out'), signout_path, method: "delete"
        - else
          %li= link_to t('.sign_in'), signin_path

    %div.localization
      %p.locale
        = link_to image_tag("Russia.png", alt: "", title: "Русский"), locale: :ru
        = link_to image_tag("United_Kingdom.png", alt: "", title: "English"), locale: :en
        %b
          = I18n.locale



